version: '3'

services:
  app:
    container_name: app_teste_2
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@database_teste2:5432/impetus_teste2
    command: npm start
    depends_on:
      - db 
    ports:
      - 3002:3002
    volumes:
      - .:/usr/app
  db:
    image: postgres:latest
    container_name: database_teste2
    restart: always
    environment:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: impetus_teste2
    volumes:
          - ./pgdata_teste2:/var/lib/postgresql/data
    ports:
          - "5432:5432"